- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install common apt packages
  become: true
  apt:
    name: "{{ packages.debian.apps }}"
    state: present

- name: Install Oh My Zsh
  import_tasks: apps/oh-my-zsh.yml
- name: Install LinuxBrew
  import_tasks: apps/linux/brew.yml
- name: Install Chezmoi
  import_tasks: apps/linux/chezmoi.yml
