- name: Install packages with brew
  community.general.homebrew:
    name:
      - bat
      - curl
      - delta
      - direnv
      - fzf
      - gh
      - git
      - htop
      - lsd
      - neovim
      - tmux
      - tree
      - wget
      - zoxide
      - zsh
    state: present
