- name: Gather facts about the system
  become: yes
  setup:
    gather_subset:
      - "!user"

- name: Gather facts about the user
  setup:
    gather_subset:
      - "user"

- name: Install common packages in Debian
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install common packages in macOS
  import_tasks: macos.yml
  when: ansible_os_family == "Darwin"
