- name: Install Oh My Zsh # noqa: latest
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install Powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
